name: Publish Package to NPMjs

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/setup
        with:
          regular-install: true
      - name: Get release run id
        id: release_run_id
        run: echo RELEASE_RUN_ID=${{ github.event.release.id }} >> $GITHUB_OUTPUT
      - uses: ./.github/actions/download-artifact
        with:
          artifact: dist
          path: dist

          run-id: ${{ steps.release_run_id.outputs.RELEASE_RUN_ID }}
      - uses: ./.github/actions/download-artifact
        with:
          artifact: package_json
          run-id: ${{ steps.release_run_id.outputs.RELEASE_RUN_ID }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
